/*
Find the Difference

Solution
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        
        // Build/Maintain frequency table for s and t
        // check fo the difference in the freq table to detect which one was added in to t
        
        int sFreq[26] = {0}, tFreq[26] = {0};
        int i, n;

        /*
        n = s.length();
        for (i = 0; i < n; i++)
            sFreq[s[i] - 'a']++;

        n = t.length();
        for (i = 0; i < n; i++)
            tFreq[t[i] - 'a']++;

        */
        
        // Combine these two loops in single with condition to minimize 
        int slen = s.length(), tlen = t.length();
        n = min(slen, tlen);
        for (i = 0; i < n; i++)
        {
            sFreq[s[i] - 'a']++;
            tFreq[t[i] - 'a']++;
        }

        while (i < slen)
        {
            sFreq[s[i] - 'a']++;
            i++;
        }
        
        while (i < tlen)
        {
            tFreq[t[i] - 'a']++;
            i++;
        }
        
        // Now Freq tables are ready; compare one with other and find out which letter added to t
        for (i = 0 ; i < 26; i++)
        {
            if (tFreq[i] > sFreq[i])
            {
                return i + 'a';
            }
        }
        
        return -1;
    }
    
    /*
    54 / 54 test cases passed.
Status: Accepted
Runtime: 4 ms
Memory Usage: 6.8 MB
Submitted: 0 minutes ago

    */
};
